### ISSUE TITLE
Add logging flag as a simple boolean & as a callback function

### ISSUE THREAD

**Issue by Oskar-V** [outl1ne/nova-openai#15]
# Feature
Add a callback function to run requests to determine if the requests should be logged to the local database.
In case of OpenAIs assistants API polling must be used to determine when the response is ready. Meaning a lot of useless queries will fill up the database. 
## Example of polling polluting the database:
![image](https://github.com/outl1ne/nova-openai/assets/26824310/9bc882ec-6ec2-40c3-b3a7-1e17e23bc126)

## Example of using a callback to prevent populating the database:
```php
// If message is not yet completed don't log the request to the database
function logPrompt (mixed $response): bool {
	return $response['status'] === 'complete';
}

$thread = (new OpenAI())>threads();
$status = $thread->run(logPrompt)->retrieve($thread_id, $run_id)->meta['status'];
```
_The above example is not valid PHP just an pseudo codeish example of usage case_

**Comment by allantatter** [comment]
https://github.com/outl1ne/nova-openai/releases/tag/0.4.0

```
OpenAI::chat()->shouldStore(fn () => false)->create(
    model: 'gpt-3.5-turbo',
    messages: (new Messages)->system('You are a helpful assistant.')->user('Hello!'),
);
```
