### ISSUE TITLE
Add file functionality for assistants

### ISSUE THREAD

**Issue by Oskar-V** [outl1ne/nova-openai#30]
Please implement the following endpoints:

- [CreateAssistantFile](https://platform.openai.com/docs/api-reference/assistants/createAssistantFile)
- [ListAsssitantFiles](https://platform.openai.com/docs/api-reference/assistants/listAssistantFiles)
- [DeleteAssistantFile](https://platform.openai.com/docs/api-reference/assistants/deleteAssistantFile)

**Comment by allantatter** [comment]
https://github.com/outl1ne/nova-openai/releases/tag/0.5.1
updated readme: https://github.com/outl1ne/nova-openai?tab=readme-ov-file#assistants
