### ISSUE TITLE
Log Full Exception Message from Chat Completions Endpoint

### ISSUE THREAD

**Issue by KasparRosin** [outl1ne/nova-openai#70]
<img width="1322" alt="image" src="https://github.com/user-attachments/assets/34e3a972-2458-4163-8b74-c2006184516f">

Currently, when an error is returned from the Chat completions endpoint, our application logs and displays a truncated error message. However, the full exception details are accessible via $e->getResponse()->getBody()->getContents().

**Comment by allantatter** [comment]
The package rethrows the Guzzle's ClientException as it was thrown originally. Do you mean that we should create our own ClientException class that would not truncate the error message and throw that instead? At least this PR should log the entire error into the database for the reqeust record: https://github.com/outl1ne/nova-openai/pull/71/files

**Comment by KasparRosin** [comment]
![image](https://github.com/user-attachments/assets/99566360-30be-4eea-83ab-380578f1bfa8)

The original Guzzle's ClientExceptions $message is summarised as seen on the image. I think making our own exception is something we can consider in the future, but for now I think re-throwing the exception is fine.

The main issue at the moment resided specifically in accessing the exception message in logs and nova resource.
